version: '3'
services:
  questdb:
    image: questdb/questdb
    ports:
      - "8812:8812" # Web console
      - "9000:9000" # REST API
      - "9009:9009" # PostgreSQL wire protocol
    environment:
      - QDB_SERVER_HTTP_MIN_ENABLED=true
      - QDB_SERVER_PG_ENABLED=true
